language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.9

cache:

  directories:
    - ~/.npm
    - ~/.cache

before_script:
  - ng serve --open


script:
  - npx cypress run --record