language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

cache:

  directories:
    - ~/.npm
    - ~/.cache


defaults: &defaults
  script:
    - npx cypress run --record