language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.9

cache:

  directories:
    - ~/.npm
    - ~/.cache

install:
  # use the new "ci" command for fastest installs on CI
  - npm ci

before_script:
  - ng serve --open &


script:
  - $(npm bin)/cypress run --record